Symptom records view
dsantibanezvera/lcm-sayu pull request #14
Opened 2020-11-26 17:04 UTC by danielacortesthoughtworkks

Created symptoms record views and appropriate tests.

2020-11-26 18:51 UTC, brokarth requested changes

2020-11-26 18:51 UTC, brokarth commented on src/components/SymptomsDailyValues/SymptomsDailyValues.tsx
> +  <Box mb={2} className={styles.symptomBox}>
Cual es la diferencia entre este box y el div que estabajo? por que se separan?

2020-11-26 18:51 UTC, brokarth commented on src/components/SymptomsDailyValues/symptomsDailyValues.module.scss
> +.symptomBox {
Se debe respetar la jerarquia de los elementos, si .symptomList esta dentro de .symptomBox en el html, en el scss tambien deberian estar anidados, y asi para las demas clases

2020-11-26 18:51 UTC, brokarth commented on src/components/SymptomsDailyValues/symptomsDailyValues.module.scss
> +.dolor_value {
Si lo unico que cambia entre los *_value es el color, entonces hagan una clase general que englobe los atributos en comun y para los cambios especificos hacen clases especificas.

Otra cosa, los naiming en css estan con dash-case, no snake_case

2020-11-26 18:51 UTC, brokarth commented on src/components/SymptomsLegend/SymptomsLegend.tsx
> +    <Stack isInline spacing={16}>
Que proposito tienen los dos stack seguidos si encierran lo mismo?

2020-11-26 18:51 UTC, brokarth commented on src/components/SymptomsLegend/symptomslegend.module.scss
> +.dolor_legend {
mismos comentarios que en symptomsDailyValues.module.scss

2020-11-26 18:51 UTC, brokarth commented on src/components/TitleHeader/TitleHeader.tsx
> +import { Navigation } from '../Navigation/Navigation'
No ocupar import relativos a menos que esten en la misma carpeta, para todo lo demas, siempre debemos comenzar con src/...

2020-11-26 18:51 UTC, brokarth commented on test/pages/_error.test.tsx
> +        /Ha ocurrido un error, espera unos minutos e inténtalo nuevamente/i
agregar ^ y $ a la expresion regular para que la busqueda sea exacta

2020-11-26 18:51 UTC, brokarth commented on test/pages/ver_registros_sintomas/ver-registros-sintomas.test.tsx
> +import React from 'react'
El nombre de la carpeta debe ser con dash-case, no snake_case

2020-11-26 20:08 UTC, danielacortesthoughtworkks commented on src/components/SymptomsLegend/SymptomsLegend.tsx
> +    <Stack isInline spacing={16}>
Uno es la fila y los dos de adentro son columnas.

2020-11-26 20:14 UTC, brokarth commented on src/components/SymptomsLegend/SymptomsLegend.tsx
> +    <Stack isInline spacing={16}>
Tienes razon, en ese caso, seria mejor usar una grilla (que tiene dos dimensiones) en vez de una caja flexible (que es unidimensional).

Otra cosa, el fragment no es necesario, ya que el primer Stack envuelve todo

2020-11-27 14:12 UTC, brokarth approved these changes

2020-11-27 14:13 UTC, merged