80 register and show rescate
dsantibanezvera/lcm-sayu pull request #21
Opened 2020-12-01 22:17 UTC by BereniceHerrera

WIP of Rescate RadioButton of
<img width="514" alt="Screen Shot 2020-12-01 at 19 11 27" src="https://user-images.githubusercontent.com/70540312/100803359-cf2b3f00-3409-11eb-880c-a42b687418b1.png">
 symptoms registry

2020-12-02 12:53 UTC, danielacortesthoughtworkks approved these changes
¿Las migraciones para ingresar el rescate en la base de datos se hará en otra card?

2020-12-03 14:17 UTC, danielacortesthoughtworkks reviewed
? styles['symptom-list'] + ' ' + styles['with-rescue']

La concatenación se puede hacer de otra manera. 
Por ejemplo: <div className={`${styles['tragar-legend']} ${styles['legend']}`}

2020-12-03 16:02 UTC, brokarth requested changes

2020-12-03 16:02 UTC, brokarth commented on src/steps/SymptomsRegistry/SymptomsRegistry.tsx
> +    constipacion: parseInt(data['Deposiciones'], 10) as number,
ya se envio una correccion para esto, les recomiendo que lo saquen o tendran conflictos

2020-12-03 20:28 UTC, BereniceHerrera commented
> ? styles['symptom-list'] + ' ' + styles['with-rescue']
> 
> La concatenación se puede hacer de otra manera.
> Por ejemplo: <div className={`${styles['tragar-legend']} ${styles['legend']}`}

done!

2020-12-03 20:29 UTC, BereniceHerrera commented
> ¿Las migraciones para ingresar el rescate en la base de datos se hará en otra card?

ready!

2020-12-04 13:19 UTC, danielacortesthoughtworkks approved these changes

2020-12-04 15:22 UTC, merged