117 view cuidadores button
dsantibanezvera/lcm-sayu pull request #25
Opened 2020-12-07 15:49 UTC by danielacortesthoughtworkks

Agregar lógica para ver lista de cuidadores con nombre.

2020-12-07 20:12 UTC, BereniceHerrera approved these changes

2020-12-07 20:32 UTC, dsantibanezvera requested changes

2020-12-07 20:32 UTC, dsantibanezvera commented on src/model/Carer.ts
> +export type Carer = {
Dado que no existe una tabla Carer o Cuidador ¿Este type no será un DTO?

2020-12-07 20:44 UTC, danielacortesthoughtworkks commented on test/pages/tratante/ver-cuidadores.test.tsx
> +  test('should show show last updated when it is null', async () => {
Fixed

2020-12-07 20:55 UTC, BereniceHerrera reviewed
![image](https://user-images.githubusercontent.com/70540312/101404245-23746a00-38b5-11eb-84f5-d429da7cd0c8.png)
Chic@s, se me pasó decirles que la gente de la cmunidad UX nos reocmendó usar imágenes  con formato .svg, en lugar de png porque  svg  se adapta a todos los  navegadores y tamaños de resolución

2020-12-09 12:37 UTC, brokarth commented on src/model/Carer.ts
> +export type Carer = {
Esto es un objeto de negocio que no tiene persistencia, solo existe cuando el sistema esta vivo, se basa a partir del usuario que tenemos mas informacion enriquecida, un dto es solo un objeto para mover entre fronteras

2020-12-09 14:17 UTC, merged