130 registro exitoso
dsantibanezvera/lcm-sayu pull request #6
Opened 2020-10-20 19:46 UTC by danielacortesthoughtworkks

Creación de pantalla de registro exitoso de síntomas, con pruebas unitarias y de integración. 
<img width="791" alt="Captura de Pantalla 2020-10-20 a la(s) 16 43 48" src="https://user-images.githubusercontent.com/51415528/96636399-a3d61000-12f3-11eb-994d-d4580d34a776.png">
<img width="344" alt="Captura de Pantalla 2020-10-20 a la(s) 16 42 09" src="https://user-images.githubusercontent.com/51415528/96636468-b5b7b300-12f3-11eb-996e-d85e1cd07813.png">

2020-10-20 19:58 UTC, brokarth requested changes

2020-10-20 19:58 UTC, brokarth commented on ui/src/steps/FaceScaleScreen/FaceScaleScreen.jsx
> +
Remove unnecessary line please.

2020-10-20 20:23 UTC, brokarth approved these changes

2020-10-21 19:39 UTC, brokarth approved these changes

2020-10-21 19:42 UTC, brokarth requested changes

2020-10-21 19:42 UTC, brokarth commented on ui/src/steps/FaceScaleScreen/FaceScaleScreen.jsx
> +
please remove

2020-10-22 16:03 UTC, brokarth approved these changes
Aprobare, pero ojo con el codigo eliminado, se debe eliminar eventualmente

2020-10-27 15:42 UTC, dsantibanezvera approved these changes

2020-10-27 16:31 UTC, merged